apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: airport-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}(/|$)(.*)$
            pathType: Prefix
            backend:
              service:
                name: airport-backend-service
                port:
                  number: 8080