apiVersion: v1
kind: Service
metadata:
  name: airport-backend-service
spec:
  selector:
    app: airport-backend-deployment
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: airport-postgres-service
spec:
  selector:
    app: airport-backend-postgres-deployment
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432