image:
  repository: ghcr.io/2223-5ahif-nvs/03-lab-android-simple-room-db-microproject-s1mple133
  pullPolicy: Always
  tag: latest

ingress:
  host: student.cloud.htl-leonding.ac.at
  path: d.pavelescu/airport-backend

