name: CD

on:
  push:
    branches:
      - "main"

env:
  HELM_RELEASE_NAME: airport-backend
  DEPLOYMENT_NAME: airport-backend-deployment

jobs:
  build:
    name: Build Backend
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      QUARKUS_DATASOURCE_REACTIVE_URL: postgresql://localhost:5432/postgres

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Convert github repository name to lowercase
        run: echo "IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Convert github registry name to lowercase
        run: echo "IMAGE_REGISTRY=$(echo ${{ env.REGISTRY }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV && ls -al .

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to GitHub Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Quarkus Native Application
        run: |
          cd ./backend
          ./mvnw package -Pnative -Dquarkus.native.container-build=true

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          file: ./backend/src/main/docker/Dockerfile.native-micro
          context: backend
          push: true
          tags: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}:latest

  deploy:
    name: Deploy Backend to Leocloud
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.25.4'

      - name: Setup Helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.10.2'

      - name: Install oidc plugin for kubectl
        run: |
          wget https://github.com/int128/kubelogin/releases/download/v1.25.3/kubelogin_linux_amd64.zip
          mkdir kubelogin
          unzip kubelogin_linux_amd64.zip -d kubelogin
          mv kubelogin/kubelogin kubelogin/kubectl-oidc_login
          echo $(pwd)/kubelogin >> $GITHUB_PATH

      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - name: Upgrade Helm Deployment # to update k8s manifests in the leocloud cluster, doesn't trigger image pull
        run: helm upgrade --install ${{ env.HELM_RELEASE_NAME }} ./helm --namespace ${{ secrets.LEOCLOUD_NAMESPACE }}
      - name: Rollout Restart Deployment # Used to trigger image pull action in the leocloud
        run: kubectl rollout restart deployment ${{ env.DEPLOYMENT_NAME }} --namespace=${{ secrets.LEOCLOUD_NAMESPACE }}